### PR TITLE
fix `indexHTML` broken when `NODE_ENV=production`

### LINKED ISSUE #37: [IMPORTANT] [BUG] `indexHTML` option is broken in latest version
>[!IMPORTANT]
> This bug only appears when `NODE_ENV=production`

## Folder structure
```text
| - public
  | - index.html
  | - test
    | - index.html
| - test.ts
```

## Files
**index.html** -> fill in with any generic HTML content.

```ts
// test.ts
import { Elysia } from 'elysia';
import { staticPlugin } from '@elysiajs/static';

const port = 8080;
const hostname = '0.0.0.0';

const app = new Elysia()
  .use(staticPlugin({ prefix: '/', indexHTML: true }))
  .listen({ port, hostname });

console.log(`Server started at ${app.server?.url}`);
```

> [!NOTE]
> `indexHTML` is `true` by default, but I set it to true explicitly anyways

## Versions
1. `Bun` -> 1.1.31
2. `elysia` -> 1.1.20
3. `@elysiajs/static` -> 1.1.1

## Tests
1. `GET http://localhost:8080/` -> **(redirect)** `http://localhost:8080` -> `NOT_FOUND`
2. `GET http://localhost:8080` -> `NOT_FOUND`
3. `GET http://localhost:8080/test` -> `NOT_FOUND`
4. `GET http://localhost:8080/test/` -> `NOT_FOUND`
5. `GET http://localhost:8080/index.html` -> **Works**
6.  `GET http://localhost:8080/test/index.html` -> **Works**

## Conclusion
`indexHTML` option in all broken in all shape and form is the latest version. After some testing, the last working version is **1.0.3**.

### PR DESCRIPTION
**Pull request by touhidurrr**
fixes #37

### CODE REVIEW

**Comment by touhidurrr** [comment]
@arch-fan, can you test if this pr fixes your issue also?

**Comment by arch-fan** [comment]
Nope, it doesn't

**Comment by RafalGoslawski** [comment]
This doesn't solve the issue. The issue is known by the author, see commented out test in https://github.com/elysiajs/elysia-static/blob/main/test/index.test.ts#L414-L425

If you uncomment this test, it still fails with your change. I'm having a look into a proper fix.

**Comment by RafalGoslawski** [comment]
I've proposed a fix in #40 if you'd like to try if it fixes it for you.

**Comment by touhidurrr** [comment]
Nice @RafalGoslawski, if it gets fix then I am happy.

**Comment by touhidurrr** [comment]
Closed on favor of #40

**Pull request closed without merging**
